baseurl = "https://katherineschneider.netlify.com/"
languageCode = "en-us"
title = "Katherine Schneider's Blog"
# Define how many pages appear per site
paginate = 10
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Katherine Schneider"
    site_description = "The awesome blog of John Doe."
    location = "Mercyhurst University"
    # Link custom assets relative to /static
    avatar = "img/profile2.png"
    header_background = "img/stars.jpg"
    header_title = "Katie's Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    linkedin  = "Katherine Schneider"
    github    = "katieschneider"